extends RefCounted

# GERADO por tools/gerar_precarga.py — não editar à mão.
# Arquivos que cada tela carrega no _ready; a TransicaoGlobal os pede
# numa thread junto com a cena.

const LISTA := {
	"res://scenes/admin.tscn": [
		"res://fonts/Exo2-ExtraBold.ttf",
	],
	"res://scenes/arena.tscn": [
		"res://entities/LanternaVermelha.tscn",
		"res://entities/LanternaVerde.tscn",
		"res://entities/LanternaAzul.tscn",
		"res://songs/arena_song.mp3",
		"res://songs/plasma-hit.mp3",
		"res://songs/lazer-charge.mp3",
		"res://songs/bullet_no.mp3",
		"res://songs/alvo_crash.mp3",
		"res://songs/hit-lamp.mp3",
		"res://songs/bip.mp3",
		"res://songs/bip-error.mp3",
		"res://fonts/Exo2-ExtraBold.ttf",
		"res://info_scenes/info_arena.png",
	],
	"res://scenes/bar.tscn": [
		"res://fonts/Exo2-Bold.ttf",
		"res://fonts/Exo2-ExtraBold.ttf",
		"res://entities/GarrafaGin.tscn",
		"res://entities/GarrafaRum.tscn",
		"res://entities/GarrafaVodka.tscn",
		"res://entities/GarrafaWhisky.tscn",
		"res://songs/recharge.mp3",
		"res://songs/song-oldwest.mp3",
		"res://entities/garrafa.tscn",
		"res://songs/end_game.mp3",
		"res://songs/bullet_no.mp3",
		"res://songs/fail.mp3",
		"res://songs/smash.mp3",
		"res://songs/tiro-de-pistola.mp3",
		"res://info_scenes/bar_info.png",
	],
	"res://scenes/cenarios.tscn": [
		"res://songs/tiro-de-pistola.mp3",
		"res://songs/theme.ogg",
		"res://songs/choice.mp3",
		"res://sprites/cene_desert.png",
		"res://sprites/cene_mar.png",
		"res://sprites/cene_bar.png",
		"res://sprites/cene_arena.png",
		"res://background_video/teaser_desert.ogv",
		"res://background_video/teaser_mar.ogv",
		"res://background_video/teaser_bar.ogv",
		"res://background_video/teaser_arena.ogv",
		"res://fonts/Exo2-Bold.ttf",
		"res://background_video/back_init.ogv",
	],
	"res://scenes/deserto.tscn": [
		"res://fonts/Exo2-Bold.ttf",
		"res://fonts/Exo2-ExtraBold.ttf",
		"res://sprites/deserto_sol.png",
		"res://sprites/deserto_lua.png",
		"res://sprites/deserto_sol_mascara.png",
		"res://sprites/deserto_lua_mascara.png",
		"res://songs/tiro-de-pistola.mp3",
		"res://songs/recharge.mp3",
		"res://songs/bullet_no.mp3",
		"res://songs/end_game.mp3",
		"res://songs/egito.mp3",
		"res://songs/hit-sun.mp3",
		"res://songs/hit-moon.mp3",
		"res://info_scenes/desert_info.png",
	],
	"res://scenes/main.tscn": [
		"res://background_video/back_init.ogv",
		"res://background_video/teaser_arena.ogv",
		"res://background_video/teaser_bar.ogv",
		"res://background_video/teaser_mar.ogv",
		"res://background_video/teaser_desert.ogv",
		"res://songs/audio_intro.mp3",
		"res://songs/init.wav",
	],
	"res://scenes/mar.tscn": [
		"res://sprites/atlantis.png",
		"res://songs/buble_hit.mp3",
		"res://songs/xploit.mp3",
		"res://songs/recharge.mp3",
		"res://songs/bullet_no.mp3",
		"res://info_scenes/mar_info.png",
		"res://fonts/Exo2-Bold.ttf",
		"res://fonts/Exo2-ExtraBold.ttf",
		"res://songs/end_game.mp3",
		"res://songs/tiro-de-pistola.mp3",
		"res://songs/vaso_hit.mp3",
		"res://songs/bau_hit.mp3",
		"res://songs/pirate.mp3",
	],
	"res://scenes/ranking.tscn": [
		"res://songs/ranking-song.mp3",
		"res://background_video/back_init.ogv",
	],
}
